name: Extract captions
description: Save the captions from a vieo
title: "Extract captions"
labels: ["captions"]
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: URL to an article or video
    validations:
      required: true
