name: Ensure labels
on: [push]

jobs:
  ensure_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Create labels
      uses: actions/github-script@v6
      with:
        script: |
          try {
            github.rest.issues.createLabel({
              ...context.repo,
              name: 'captions'
            })
            github.rest.issues.createLabel({
              ...context.repo,
              name: 'whisper'
            })
          } catch() {
            // Ignore if labels exist already
          }
